# データベース接続設定
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/message_app
    username: fujioka
    password: kurukuru331
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring:
#  datasource:
#    url: jdbc:mysql://message-app-db.ctg0u2ka4riw.ap-northeast-1.rds.amazonaws.com:3306/message_app
#    username: fujioka
#    password: kurukuru331
#    driver-class-name: com.mysql.cj.jdbc.Driver

# JPAの設定
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# メールの設定
  mail:
    host: smtp.gmail.com
    port: 587
    username: shukatu331@gmail.com
    password: vgzhlbqhqojsbaaz
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true